### ISSUE TITLE
Некорректная нумерация заданий по вариантам (lab01)

### ISSUE THREAD

**Issue by Skriep** [avl-bsuir/csa-2022#1]
В файле README.md лабораторной работы lab01 следующая структура заданий:
- Задание 0. Введение
- Задание 1: Подсхемы
- Задание 2: Хранение состояния.
- Задание 3: Практика с разветвителями
- Задание 4: Реализация выражений булевой алгебры.
- - Вариант 1
- - Вариант 2
- - ...
- - Вариант 20
- Упражнение 6, Вариант 1: Реализация сложных комбинационных схем.
- Задание 5, Вариант 2: Реализация сложных комбинационных схем.
- Упражнение 6, Вариант 3: Реализация сложных комбинационных схем.
- Упражнение 6, Вариант 4: Реализация сложных комбинационных схем.
- ...
- Упражнение 6, Вариант 10: Реализация сложных комбинационных схем.

#### Также имеется следующий раздел перед заданиями по вариантам:

Задания по вариантам.
Ниже представлены два упражнения по вариантам в них необходимо составить рабочие схемы ex5.circ и ex6.circ, решающие поставленную задачу. Описания некоторых упражнений представлены в книге Харрис и Харрис ЦИФРОВАЯ СХЕМОТЕХНИКА И АРХИТЕКТУРА КОМПЬЮТЕРА: RISC-V

---

Корректный порядок заданий:
- Задание 0: Введение.
- Задание 1: Подсхемы.
- Задание 2: Хранение состояния.
- Задание 3: Практика с разветвителями.
- Задание 4: Реализация выражений булевой алгебры.
- - Вариант 1
- - Вариант 2
- - ...
- - Вариант 20
- Задание 5: Реализация сложных комбинационных схем.
- - Вариант 1
- - Вариант 2
- - ...
- - Вариант 10

#### Корректный раздел перед заданиями по вариантам (изменения выделены жирным):

Задания по вариантам.
Ниже представлены два упражнения по вариантам. В них необходимо составить рабочие схемы **ex4.circ** и **ex5.circ**, решающие поставленную задачу. Описания некоторых упражнений представлены в книге Харрис и Харрис ЦИФРОВАЯ СХЕМОТЕХНИКА И АРХИТЕКТУРА КОМПЬЮТЕРА: RISC-V.

**Comment by avl-bsuir** [comment]
Отличное замечание!
В следующий раз можно приложить патч описания. Для этого нужно поправить текст задания а потом набрать команду 
```
git diff > fixes.patch
```
В файле `fixes.patch` будут только внесенные изменения.
